app = "solosuccess-ai"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 25

  [[http_service.ports]]
    port = 80

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]


