name: Deploy (Deno Deploy)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}
      DENO_PROJECT: ${{ secrets.DENO_PROJECT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build static assets
        run: npm run build
      - name: Deploy to Deno Deploy
        if: ${{ env.DENO_DEPLOY_TOKEN != '' && env.DENO_PROJECT != '' }}
        uses: denoland/deployctl@v1
        with:
          project: ${{ env.DENO_PROJECT }}
          entrypoint: server.ts
          token: ${{ env.DENO_DEPLOY_TOKEN }}


